### ISSUE TITLE
Uncorrect pitch values detected above the camera

### ISSUE THREAD

**Issue by darkcurrent** [glefundes/mobile-facegaze#1]
Hello, 

First of all I have to say that your lightweight implementation is really cool.

I noticed something, when I look above the camera the pitch is remains nearly the same as when I look into the camera. It has to be give bigger results. Then I realized that all of the database contains laptop video recording. That means all of the data is recorded gazes below the camera. So I think my situation is normal, am I right? Does your model gives same results on your system?

Second question is: The model outputs pitch and raw floats. What is the unit of these numbers?

Thank you...

**Comment by glefundes** [comment]
Yes, you diagnosed the issue correctly. The dataset used for the pre-trained weights is rather limited, but it made sense as a POC since this model is an optimization of the architecture proposed in the original MPIIFaceGaze paper. 
If you wish, you can use another dataset (or record your own), and it really shouldn't be a problem to train the model from scratch or even fine-tune it with it. This way you should be able to obtain a larger range of pitch/yaw predictions.

the pitch/yaw values are in radians, If I'm not mistaken.

PS: Thank you for the facemesh/IIR suggestions on the other issues. I'll look into including them as soon as I get a break from my day job

**Comment by darkcurrent** [comment]
You are welcome.
